from docx import Document

print("=======RESUME MAKER=======")
title_input = input("Resume file title: ")
print("Please input your data accurately to generate your resume")
name = input("name: ")
email = input("email: ")
phone = input("phone number: ")
location = input("location: ")
profile = input("profile: ")
experience1 = input("experience 1: ")
experience2 = input("experience 2: ")
education = input("education: ")
degree = input("education degree and major: ")
year = input("year of: ")
skill1 = input("skill 1: ")
skill2 = input("skill 2: ")
skill3 = input("skill 3: ")
skill4 = input("skill 4: ")

document = Document()
document.add_heading(name.upper())
document.add_paragraph(email)
document.add_paragraph(phone)
document.add_paragraph(location)
document.add_paragraph("_______________________________________________________________________________________________________")
document.add_heading("PROFILE", level=1)
document.add_paragraph(profile)
document.add_heading("EXPERIENCE", level=1)
document.add_paragraph(" "+experience1, style='List Bullet')
document.add_paragraph(" "+experience2, style='List Bullet')
document.add_heading("EDUCATION", level=1)
document.add_paragraph(" "+education, style='List Bullet')
document.add_paragraph("    - "+degree)
document.add_paragraph("    - ("+year+")")
document.add_heading("SKILLS", level=1)
document.add_paragraph(" "+skill1, style='List Bullet')
document.add_paragraph(" "+skill2, style='List Bullet')
document.add_paragraph(" "+skill3, style='List Bullet')
document.add_paragraph(" "+skill4, style='List Bullet')

save = document.save(title_input+".docx")

print("Resume saved")
